server:
  port: 8003
  address: 0.0.0.0


spring:
  config:
    import: database.yml
  mvc:
    servlet:
      load-on-startup: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: llmeetllmeetllmeetllmeetllmeetllmeet
  expiration: 86400