server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/videomeeting_db
    username: root
    password: 14201607
  mvc:
    servlet:
      load-on-startup: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: PXCvv0SAWup83GdyGjQHXO0JPiamMjGCj7nKC/c8f2I=
  expiration: 86400